steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/stylesheets/app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/stylesheets/app:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'stylesheets'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/stylesheets/app:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-west1

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/stylesheets/app:$COMMIT_SHA'
