// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package cassette

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/johnfarrell/stylesheets/templates/components"

func sectionDialogs(snippets map[string]string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- snippet:modal --> <div x-data=\"{ modal: null, authCode: '', confirmed: false }\"><!-- Trigger buttons --><div class=\"flex flex-wrap gap-3 mb-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, t := range modalTriggers {
				var templ_7745c5c3_Var3 = []any{t.BtnClass}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var3...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<button class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var3).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `guides/cassette/section_15_dialogs.templ`, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, templ.Attributes{"@click": t.ResetExpr})
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, ">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(t.Label)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `guides/cassette/section_15_dialogs.templ`, Line: 12, Col: 90}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><p style=\"font-size: var(--font-size-caption); color: var(--color-text-muted);\">Click a button above to open the corresponding modal dialog.</p><!-- Overlay --><div class=\"cass-overlay\" x-show=\"modal !== null\" style=\"display: none;\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, templ.Attributes{"@click.self": "modal=null"})
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "><!-- Modal 1: Auth --><div class=\"cass-modal\" x-show=\"modal==='auth'\" style=\"display: none;\"><div class=\"cass-modal-header\">ACCESS REQUEST — LEVEL 5 CLEARANCE</div><div style=\"padding: 1.25rem; display: flex; flex-direction: column; gap: 1rem;\"><div><label class=\"cass-label\" for=\"modal-personnel\">PERSONNEL ID</label> <input id=\"modal-personnel\" type=\"text\" class=\"cass-input\" placeholder=\"e.g. RIPLEY, E. — WO-NOS-002\"></div><div><label class=\"cass-label\" for=\"modal-code\">AUTHORIZATION CODE</label> <input id=\"modal-code\" type=\"password\" class=\"cass-input cass-input-box\" placeholder=\"••••••••\"></div><div><label class=\"cass-label\" for=\"modal-level\">ACCESS LEVEL REQUESTED</label> <select id=\"modal-level\" class=\"cass-input cass-input-box\" style=\"cursor: pointer;\"><option>L-3</option> <option>L-4</option> <option>L-5</option> <option>UNRESTRICTED</option></select></div><div><label class=\"cass-label\" for=\"modal-reason\">REASON FOR ACCESS</label> <textarea id=\"modal-reason\" rows=\"2\" class=\"cass-input cass-input-box\" placeholder=\"Describe operational need for elevated access clearance...\"></textarea></div></div><div class=\"flex justify-end gap-3\" style=\"padding: 0.75rem 1.25rem; border-top: 1px solid var(--color-border);\"><button class=\"cass-btn\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, templ.Attributes{"@click": "modal=null"})
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, ">CANCEL</button> <button class=\"cass-btn cass-btn-filled\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, templ.Attributes{"@click": "modal=null"})
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, ">SUBMIT REQUEST</button></div></div><!-- Modal 2: Jettison --><div class=\"cass-modal\" x-show=\"modal==='jettison'\" style=\"display: none; border-color: var(--color-danger);\"><div class=\"cass-modal-header cass-modal-header-danger\">CONFIRM JETTISON — IRREVERSIBLE ACTION</div><div style=\"padding: 1.25rem;\"><div class=\"cass-notice cass-notice-warning mb-4\"><div class=\"cass-notice-label\" style=\"color: var(--color-danger);\">WARNING</div><p>This action is irreversible. Once executed, the following cargo will be permanently jettisoned into open space and cannot be recovered.</p></div><p style=\"font-size: var(--font-size-caption); font-weight: 700; margin-bottom: 0.5rem; text-transform: uppercase; letter-spacing: 0.06em;\">Cargo to be jettisoned:</p><ul style=\"font-size: var(--font-size-body); color: var(--color-text-muted); margin-bottom: 1rem; padding-left: 1rem; line-height: 2;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, item := range jettisonCargo {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<li>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(item)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `guides/cassette/section_15_dialogs.templ`, Line: 60, Col: 18}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</li>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</ul><div><label class=\"cass-label\" for=\"modal-jettison-confirm\">TYPE \"CONFIRM\" TO PROCEED</label> <input id=\"modal-jettison-confirm\" type=\"text\" x-model=\"authCode\" class=\"cass-input cass-input-box\" placeholder=\"CONFIRM\" style=\"text-transform: uppercase;\"></div></div><div class=\"flex justify-end gap-3\" style=\"padding: 0.75rem 1.25rem; border-top: 1px solid var(--color-border);\"><button class=\"cass-btn\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, templ.Attributes{"@click": "modal=null"})
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, ">ABORT</button> <button class=\"cass-btn cass-btn-danger-filled\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, templ.Attributes{":disabled": "authCode !== 'CONFIRM'"})
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, templ.Attributes{"@click": "authCode==='CONFIRM' && (modal=null)"})
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, ">JETTISON</button></div></div><!-- Modal 3: Alert --><div class=\"cass-modal\" x-show=\"modal==='alert'\" style=\"display: none;\"><div class=\"cass-modal-header\">SYSTEM NOTIFICATION — PRIORITY MESSAGE</div><div style=\"padding: 1.25rem;\"><div class=\"cass-notice cass-notice-note mb-4\"><div class=\"cass-notice-label\" style=\"color: var(--color-primary);\">PRIORITY: ROUTINE</div><p>Scheduled maintenance window for atmospheric processing units 3 and 4 will commence at 0200 station time. Estimated duration: 45 minutes. Decks F and G will experience reduced atmospheric circulation during this period.</p></div><div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 0.5rem; margin-top: 0.75rem;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, c := range alertMetadataCells {
				templ_7745c5c3_Err = docCellView(c.Label, c.Value, c.ValueClass).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</div></div><div class=\"flex justify-end\" style=\"padding: 0.75rem 1.25rem; border-top: 1px solid var(--color-border);\"><button class=\"cass-btn cass-btn-filled\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, templ.Attributes{"@click": "modal=null"})
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, ">ACKNOWLEDGED</button></div></div></div></div><!-- /snippet:modal --> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SourceView(snippets["modal"]).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Section("15.0  Dialog Components", components.BadgeAlpine).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
