package guides

// Guide defines a style guide's metadata and theme tokens.
type Guide struct {
	Name        string
	Slug        string
	Description string
	FontURL     string
	// CSSVars holds all per-guide CSS custom properties.
	// Any visual property that differs between guides belongs here:
	// colors, typography, radius, shadows, borders, layout tokens, etc.
	CSSVars map[string]string
}

// All is the ordered list of registered style guides.
// Add new guides here to register them with the application.
var All = []Guide{
	{
		Name:        "Brutalist",
		Slug:        "brutalist",
		Description: "Raw, functional, unapologetic design with heavy borders and stark contrast.",
		FontURL:     "https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400&display=swap",
		CSSVars: map[string]string{
			// Colors
			"--color-primary":    "#000000",
			"--color-secondary":  "#FF0000",
			"--color-accent":     "#FFFF00",
			"--color-bg":         "#FFFFFF",
			"--color-surface":    "#F5F5F5",
			"--color-text":       "#000000",
			"--color-text-muted": "#555555",
			// Typography
			"--font-display":      "'Space Mono', monospace",
			"--font-body":         "'Space Mono', monospace",
			"--font-size-display": "3.5rem",
			"--font-size-heading": "1.75rem",
			"--font-size-body":    "1rem",
			"--font-size-caption": "0.75rem",
			// Shape
			"--radius-sm": "0px",
			"--radius-md": "0px",
			"--radius-lg": "0px",
			// Elevation/Shadows
			"--shadow-card": "4px 4px 0px #000000",
			"--shadow-btn":  "3px 3px 0px #000000",
			// Borders
			"--border-width": "2px",
			"--border-color": "#000000",
			// Layout
			"--layout-columns":    "1",
			"--layout-gap":        "2rem",
			"--content-max-width": "900px",
			"--section-padding":   "3rem 2rem",
			// Code
			"--code-bg":      "#0a0a0a",
			"--code-text":    "#f0f0f0",
			"--code-keyword": "#ff0000",
			"--code-string":  "#ffff00",
			"--code-comment": "#555555",
			"--code-number":  "#ff8800",
			"--code-tag":     "#ff0000",
			"--code-attr":    "#cccccc",
		},
	},
	{
		Name:        "Cassette",
		Slug:        "cassette",
		Description: "NASA technical document aesthetic — dense, ruled, deliberate.",
		FontURL:     "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;0,700;1,400&family=Orbitron:wght@400;700&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#f5f4ef",
			"--color-surface":     "#ffffff",
			"--color-surface-2":   "#e8e7e2",
			"--color-primary":     "#0b3d91",
			"--color-secondary":   "#1a5276",
			"--color-danger":      "#c0392b",
			"--color-caution":     "#c85200",
			"--color-text":        "#1a1a14",
			"--color-text-muted":  "#5a5a52",
			"--color-border":      "#c8c7c0",
			"--color-rule":        "#0b3d91",
			"--font-display":      "'Orbitron', sans-serif",
			"--font-body":         "'IBM Plex Mono', monospace",
			"--font-size-display": "2rem",
			"--font-size-heading": "0.875rem",
			"--font-size-body":    "0.8125rem",
			"--font-size-caption": "0.6875rem",
			"--radius-sm":         "0px",
			"--radius-md":         "2px",
			"--radius-lg":         "2px",
			"--shadow-card":       "0 1px 3px rgba(0,0,0,0.12)",
			"--shadow-btn":        "none",
			"--border-width":      "1px",
			"--border-color":      "#c8c7c0",
			"--layout-columns":    "2",
			"--layout-gap":        "1.5rem",
			"--content-max-width": "1200px",
			"--section-padding":   "2rem 2rem",
			// Code
			"--code-bg":      "#1a1814",
			"--code-text":    "#c8c7c0",
			"--code-keyword": "#4a9eff",
			"--code-string":  "#98c379",
			"--code-comment": "#5a6a52",
			"--code-number":  "#d19a66",
			"--code-tag":     "#e06c75",
			"--code-attr":    "#abb2bf",
		},
	},
	{
		Name:        "Minimal",
		Slug:        "minimal",
		Description: "Calm, spacious, single-column design with generous whitespace.",
		FontURL:     "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap",
		CSSVars: map[string]string{
			// Colors
			"--color-primary":    "#1a1a1a",
			"--color-secondary":  "#6b7280",
			"--color-accent":     "#3b82f6",
			"--color-bg":         "#fafafa",
			"--color-surface":    "#ffffff",
			"--color-text":       "#1a1a1a",
			"--color-text-muted": "#9ca3af",
			// Typography
			"--font-display":      "'Inter', sans-serif",
			"--font-body":         "'Inter', sans-serif",
			"--font-size-display": "3rem",
			"--font-size-heading": "1.5rem",
			"--font-size-body":    "1rem",
			"--font-size-caption": "0.8rem",
			// Shape
			"--radius-sm": "4px",
			"--radius-md": "8px",
			"--radius-lg": "16px",
			// Elevation
			"--shadow-card": "0 1px 3px rgba(0,0,0,0.08)",
			"--shadow-btn":  "0 1px 2px rgba(0,0,0,0.05)",
			// Borders
			"--border-width": "1px",
			"--border-color": "#e5e7eb",
			// Layout — single column, generous spacing
			"--layout-columns":    "1",
			"--layout-gap":        "4rem",
			"--content-max-width": "640px",
			"--section-padding":   "5rem 2rem",
			// Code
			"--code-bg":      "#f6f8fa",
			"--code-text":    "#24292f",
			"--code-keyword": "#0550ae",
			"--code-string":  "#0a3069",
			"--code-comment": "#6e7781",
			"--code-number":  "#953800",
			"--code-tag":     "#116329",
			"--code-attr":    "#953800",
		},
	},
	{
		Name:        "Glassmorphism",
		Slug:        "glass",
		Description: "Frosted translucent panels over deep gradients. Modern, layered, luminous.",
		FontURL:     "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#0f0f1a",
			"--color-surface":     "rgba(255,255,255,0.08)",
			"--color-surface-2":   "rgba(255,255,255,0.14)",
			"--color-primary":     "#a78bfa",
			"--color-secondary":   "#60a5fa",
			"--color-accent":      "#f472b6",
			"--color-text":        "#f1f5f9",
			"--color-text-muted":  "#94a3b8",
			"--color-border":      "rgba(255,255,255,0.15)",
			"--font-display":      "'Plus Jakarta Sans', sans-serif",
			"--font-body":         "'Plus Jakarta Sans', sans-serif",
			"--font-size-display": "3.5rem",
			"--font-size-heading": "1.5rem",
			"--font-size-body":    "1rem",
			"--font-size-caption": "0.8rem",
			"--radius-sm":         "8px",
			"--radius-md":         "16px",
			"--radius-lg":         "24px",
			"--shadow-card":       "0 8px 32px rgba(0,0,0,0.4)",
			"--shadow-btn":        "0 4px 15px rgba(167,139,250,0.3)",
			"--border-width":      "1px",
			"--border-color":      "rgba(255,255,255,0.15)",
			"--content-max-width": "1100px",
			"--section-padding":   "4rem 2rem",
			"--frost-blur":        "16px",
			"--frost-bg":          "rgba(255,255,255,0.08)",
			"--glow-primary":      "0 0 20px rgba(167,139,250,0.4)",
			// Code
			"--code-bg":      "rgba(10,10,25,0.9)",
			"--code-text":    "#f1f5f9",
			"--code-keyword": "#a78bfa",
			"--code-string":  "#86efac",
			"--code-comment": "#475569",
			"--code-number":  "#f472b6",
			"--code-tag":     "#60a5fa",
			"--code-attr":    "#94a3b8",
		},
	},
	{
		Name:        "Bento Dashboard",
		Slug:        "bento",
		Description: "Variable-span grid tiles, live HTMX metrics, SaaS dashboard patterns.",
		FontURL:     "https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,700&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#f8fafc",
			"--color-surface":     "#ffffff",
			"--color-surface-2":   "#f1f5f9",
			"--color-primary":     "#6366f1",
			"--color-secondary":   "#8b5cf6",
			"--color-accent":      "#10b981",
			"--color-danger":      "#ef4444",
			"--color-warning":     "#f59e0b",
			"--color-text":        "#0f172a",
			"--color-text-muted":  "#64748b",
			"--color-border":      "#e2e8f0",
			"--font-display":      "'DM Sans', sans-serif",
			"--font-body":         "'DM Sans', sans-serif",
			"--font-size-display": "2.5rem",
			"--font-size-heading": "1.25rem",
			"--font-size-body":    "0.9375rem",
			"--font-size-caption": "0.8125rem",
			"--radius-sm":         "8px",
			"--radius-md":         "12px",
			"--radius-lg":         "16px",
			"--shadow-card":       "0 1px 4px rgba(0,0,0,0.07), 0 0 0 1px rgba(0,0,0,0.04)",
			"--shadow-btn":        "0 1px 2px rgba(0,0,0,0.06)",
			"--border-width":      "1px",
			"--border-color":      "#e2e8f0",
			"--content-max-width": "1200px",
			"--section-padding":   "3rem 2rem",
			// Code
			"--code-bg":      "#1e1e2e",
			"--code-text":    "#e2e8f0",
			"--code-keyword": "#6366f1",
			"--code-string":  "#86efac",
			"--code-comment": "#64748b",
			"--code-number":  "#f59e0b",
			"--code-tag":     "#8b5cf6",
			"--code-attr":    "#94a3b8",
		},
	},
	{
		Name:        "Swiss International",
		Slug:        "swiss",
		Description: "Helvetica-era grid discipline. Red/black/white. Typography as the only decoration.",
		FontURL:     "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;700&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#ffffff",
			"--color-surface":     "#ffffff",
			"--color-surface-2":   "#f5f5f5",
			"--color-primary":     "#e63329",
			"--color-secondary":   "#1a1a1a",
			"--color-text":        "#1a1a1a",
			"--color-text-muted":  "#767676",
			"--color-border":      "#1a1a1a",
			"--font-display":      "'IBM Plex Sans', sans-serif",
			"--font-body":         "'IBM Plex Sans', sans-serif",
			"--font-size-display": "5rem",
			"--font-size-heading": "2rem",
			"--font-size-body":    "1rem",
			"--font-size-caption": "0.75rem",
			"--radius-sm":         "0px",
			"--radius-md":         "0px",
			"--radius-lg":         "0px",
			"--shadow-card":       "none",
			"--shadow-btn":        "none",
			"--border-width":      "2px",
			"--border-color":      "#1a1a1a",
			"--content-max-width": "1100px",
			"--section-padding":   "5rem 2rem",
			"--grid-columns":      "12",
			"--baseline":          "8px",
			// Code
			"--code-bg":      "#1a1a1a",
			"--code-text":    "#ffffff",
			"--code-keyword": "#e63329",
			"--code-string":  "#767676",
			"--code-comment": "#444444",
			"--code-number":  "#e63329",
			"--code-tag":     "#ffffff",
			"--code-attr":    "#aaaaaa",
		},
	},
}

// BySlug looks up a guide by its URL slug.
func BySlug(slug string) (Guide, bool) {
	for _, g := range All {
		if g.Slug == slug {
			return g, true
		}
	}
	return Guide{}, false
}
