package guides

import (
	"slices"
	"strings"

	"github.com/a-h/templ"
)

// Guide defines a style guide's metadata and theme tokens.
type Guide struct {
	Name        string
	Slug        string
	Description string
	FontURL     string
	// CSSVars holds all per-guide CSS custom properties.
	// Any visual property that differs between guides belongs here:
	// colors, typography, radius, shadows, borders, layout tokens, etc.
	CSSVars map[string]string
	// DarkCSSVars holds dark-mode overrides for CSS custom properties.
	// When non-nil, the guide supports a dark mode toggle.
	// Only color/shadow/border tokens that change need to be specified —
	// typography, layout, and radius tokens carry over from CSSVars.
	DarkCSSVars map[string]string
	// PageFunc renders the guide's full showcase page.
	PageFunc func(Guide, bool) templ.Component
}

// All is the ordered list of registered style guides.
// Add new guides here to register them with the application.
var All = []Guide{
	{
		Name:        "Brutalist",
		Slug:        "brutalist",
		Description: "Raw, functional, unapologetic design with heavy borders and stark contrast.",
		FontURL:     "https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400&display=swap",
		CSSVars: map[string]string{
			// Colors
			"--color-primary":    "#000000",
			"--color-secondary":  "#FF0000",
			"--color-accent":     "#FFFF00",
			"--color-bg":         "#FFFFFF",
			"--color-surface":    "#F5F5F5",
			"--color-text":       "#000000",
			"--color-text-muted": "#555555",
			// Typography
			"--font-display":      "'Space Mono', monospace",
			"--font-body":         "'Space Mono', monospace",
			"--font-mono":         "'Space Mono', monospace",
			"--font-size-display": "3.5rem",
			"--font-size-heading": "1.75rem",
			"--font-size-body":    "1rem",
			"--font-size-caption": "0.75rem",
			// Shape
			"--radius-sm": "0px",
			"--radius-md": "0px",
			"--radius-lg": "0px",
			// Elevation/Shadows
			"--shadow-card": "4px 4px 0px #000000",
			"--shadow-btn":  "3px 3px 0px #000000",
			// Borders
			"--border-width": "2px",
			"--border-color": "#000000",
			// Layout
			"--layout-columns":    "1",
			"--layout-gap":        "2rem",
			"--content-max-width": "900px",
			"--section-padding":   "3rem 2rem",
			// Code
			"--code-bg":      "#0a0a0a",
			"--code-text":    "#f0f0f0",
			"--code-keyword": "#ff0000",
			"--code-string":  "#ffff00",
			"--code-comment": "#555555",
			"--code-number":  "#ff8800",
			"--code-tag":     "#ff0000",
			"--code-attr":    "#cccccc",
		},
		DarkCSSVars: map[string]string{
			"--color-primary":    "#FFFFFF",
			"--color-secondary":  "#FF0000",
			"--color-accent":     "#FFFF00",
			"--color-bg":         "#0a0a0a",
			"--color-surface":    "#1a1a1a",
			"--color-text":       "#FFFFFF",
			"--color-text-muted": "#AAAAAA",
			"--shadow-card":      "4px 4px 0px #FFFFFF",
			"--shadow-btn":       "3px 3px 0px #FFFFFF",
			"--border-color":     "#FFFFFF",
			"--code-bg":          "#000000",
			"--code-text":        "#f0f0f0",
			"--code-keyword":     "#ff4444",
			"--code-string":      "#ffff00",
			"--code-comment":     "#666666",
			"--code-number":      "#ff8800",
			"--code-tag":         "#ff4444",
			"--code-attr":        "#cccccc",
		},
	},
	{
		Name:        "Cassette",
		Slug:        "cassette",
		Description: "NASA technical document aesthetic — dense, ruled, deliberate.",
		FontURL:     "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;0,700;1,400&family=Orbitron:wght@400;700&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#f5f4ef",
			"--color-surface":     "#ffffff",
			"--color-surface-2":   "#e8e7e2",
			"--color-primary":     "#0b3d91",
			"--color-secondary":   "#1a5276",
			"--color-danger":      "#c0392b",
			"--color-caution":     "#c85200",
			"--color-text":        "#1a1a14",
			"--color-text-muted":  "#5a5a52",
			"--color-border":      "#c8c7c0",
			"--color-rule":        "#0b3d91",
			"--font-display":      "'Orbitron', sans-serif",
			"--font-body":         "'IBM Plex Mono', monospace",
			"--font-mono":         "'IBM Plex Mono', monospace",
			"--font-size-display": "2rem",
			"--font-size-heading": "0.875rem",
			"--font-size-body":    "0.8125rem",
			"--font-size-caption": "0.6875rem",
			"--radius-sm":         "0px",
			"--radius-md":         "2px",
			"--radius-lg":         "2px",
			"--shadow-card":       "0 1px 3px rgba(0,0,0,0.12)",
			"--shadow-btn":        "none",
			"--border-width":      "1px",
			"--border-color":      "#c8c7c0",
			"--layout-columns":    "2",
			"--layout-gap":        "1.5rem",
			"--content-max-width": "1200px",
			"--section-padding":   "2rem 2rem",
			// Code
			"--code-bg":      "#1a1814",
			"--code-text":    "#c8c7c0",
			"--code-keyword": "#4a9eff",
			"--code-string":  "#98c379",
			"--code-comment": "#5a6a52",
			"--code-number":  "#d19a66",
			"--code-tag":     "#e06c75",
			"--code-attr":    "#abb2bf",
		},
		DarkCSSVars: map[string]string{
			"--color-bg":         "#1a1814",
			"--color-surface":    "#2a2820",
			"--color-surface-2":  "#3a3830",
			"--color-primary":    "#4a9eff",
			"--color-secondary":  "#6ba3d6",
			"--color-danger":     "#ff6b5b",
			"--color-caution":    "#f0a030",
			"--color-text":       "#d4d3cc",
			"--color-text-muted": "#8a8a82",
			"--color-border":     "#4a4940",
			"--color-rule":       "#4a9eff",
			"--shadow-card":      "0 1px 3px rgba(0,0,0,0.4)",
			"--border-color":     "#4a4940",
			"--code-bg":          "#0f0e0a",
			"--code-text":        "#c8c7c0",
			"--code-keyword":     "#4a9eff",
			"--code-string":      "#98c379",
			"--code-comment":     "#5a6a52",
			"--code-number":      "#d19a66",
			"--code-tag":         "#e06c75",
			"--code-attr":        "#abb2bf",
		},
	},
	{
		Name:        "Minimal",
		Slug:        "minimal",
		Description: "Calm, spacious, single-column design with generous whitespace.",
		FontURL:     "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap",
		CSSVars: map[string]string{
			// Colors
			"--color-primary":    "#1a1a1a",
			"--color-secondary":  "#6b7280",
			"--color-accent":     "#3b82f6",
			"--color-bg":         "#fafafa",
			"--color-surface":    "#ffffff",
			"--color-text":       "#1a1a1a",
			"--color-text-muted": "#9ca3af",
			// Typography
			"--font-display":      "'Inter', sans-serif",
			"--font-body":         "'Inter', sans-serif",
			"--font-mono":         "'Courier New', Courier, monospace",
			"--font-size-display": "3rem",
			"--font-size-heading": "1.5rem",
			"--font-size-body":    "1rem",
			"--font-size-caption": "0.8rem",
			// Shape
			"--radius-sm": "4px",
			"--radius-md": "8px",
			"--radius-lg": "16px",
			// Elevation
			"--shadow-card": "0 1px 3px rgba(0,0,0,0.08)",
			"--shadow-btn":  "0 1px 2px rgba(0,0,0,0.05)",
			// Borders
			"--border-width": "1px",
			"--border-color": "#e5e7eb",
			// Layout — single column, generous spacing
			"--layout-columns":    "1",
			"--layout-gap":        "4rem",
			"--content-max-width": "640px",
			"--section-padding":   "5rem 2rem",
			// Code
			"--code-bg":      "#f6f8fa",
			"--code-text":    "#24292f",
			"--code-keyword": "#0550ae",
			"--code-string":  "#0a3069",
			"--code-comment": "#6e7781",
			"--code-number":  "#953800",
			"--code-tag":     "#116329",
			"--code-attr":    "#953800",
		},
		DarkCSSVars: map[string]string{
			"--color-primary":    "#e5e7eb",
			"--color-secondary":  "#9ca3af",
			"--color-accent":     "#60a5fa",
			"--color-bg":         "#111111",
			"--color-surface":    "#1a1a1a",
			"--color-text":       "#e5e7eb",
			"--color-text-muted": "#6b7280",
			"--shadow-card":      "0 1px 3px rgba(0,0,0,0.3)",
			"--shadow-btn":       "0 1px 2px rgba(0,0,0,0.2)",
			"--border-color":     "#333333",
			"--code-bg":          "#0d1117",
			"--code-text":        "#e6edf3",
			"--code-keyword":     "#79c0ff",
			"--code-string":      "#a5d6ff",
			"--code-comment":     "#8b949e",
			"--code-number":      "#ffa657",
			"--code-tag":         "#7ee787",
			"--code-attr":        "#ffa657",
		},
	},
	{
		Name:        "Glassmorphism",
		Slug:        "glass",
		Description: "Frosted translucent panels over deep gradients. Modern, layered, luminous.",
		FontURL:     "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#0f0f1a",
			"--color-surface":     "rgba(255,255,255,0.08)",
			"--color-surface-2":   "rgba(255,255,255,0.14)",
			"--color-primary":     "#a78bfa",
			"--color-secondary":   "#60a5fa",
			"--color-accent":      "#f472b6",
			"--color-text":        "#f1f5f9",
			"--color-text-muted":  "#94a3b8",
			"--color-border":      "rgba(255,255,255,0.15)",
			"--font-display":      "'Plus Jakarta Sans', sans-serif",
			"--font-body":         "'Plus Jakarta Sans', sans-serif",
			"--font-mono":         "'Courier New', Courier, monospace",
			"--font-size-display": "3.5rem",
			"--font-size-heading": "1.5rem",
			"--font-size-body":    "1rem",
			"--font-size-caption": "0.8rem",
			"--radius-sm":         "8px",
			"--radius-md":         "16px",
			"--radius-lg":         "24px",
			"--shadow-card":       "0 8px 32px rgba(0,0,0,0.4)",
			"--shadow-btn":        "0 4px 15px rgba(167,139,250,0.3)",
			"--border-width":      "1px",
			"--border-color":      "rgba(255,255,255,0.15)",
			"--content-max-width": "1100px",
			"--section-padding":   "4rem 2rem",
			"--frost-blur":        "16px",
			"--frost-bg":          "rgba(255,255,255,0.08)",
			"--glow-primary":      "0 0 20px rgba(167,139,250,0.4)",
			// Code
			"--code-bg":      "rgba(10,10,25,0.9)",
			"--code-text":    "#f1f5f9",
			"--code-keyword": "#a78bfa",
			"--code-string":  "#86efac",
			"--code-comment": "#475569",
			"--code-number":  "#f472b6",
			"--code-tag":     "#60a5fa",
			"--code-attr":    "#94a3b8",
		},
	},
	{
		Name:        "Bento Dashboard",
		Slug:        "bento",
		Description: "Variable-span grid tiles, live HTMX metrics, SaaS dashboard patterns.",
		FontURL:     "https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,700&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#f8fafc",
			"--color-surface":     "#ffffff",
			"--color-surface-2":   "#f1f5f9",
			"--color-primary":     "#6366f1",
			"--color-secondary":   "#8b5cf6",
			"--color-accent":      "#10b981",
			"--color-danger":      "#ef4444",
			"--color-warning":     "#f59e0b",
			"--color-text":        "#0f172a",
			"--color-text-muted":  "#64748b",
			"--color-border":      "#e2e8f0",
			"--font-display":      "'DM Sans', sans-serif",
			"--font-body":         "'DM Sans', sans-serif",
			"--font-mono":         "'Courier New', Courier, monospace",
			"--font-size-display": "2.5rem",
			"--font-size-heading": "1.25rem",
			"--font-size-body":    "0.9375rem",
			"--font-size-caption": "0.8125rem",
			"--radius-sm":         "8px",
			"--radius-md":         "12px",
			"--radius-lg":         "16px",
			"--shadow-card":       "0 1px 4px rgba(0,0,0,0.07), 0 0 0 1px rgba(0,0,0,0.04)",
			"--shadow-btn":        "0 1px 2px rgba(0,0,0,0.06)",
			"--border-width":      "1px",
			"--border-color":      "#e2e8f0",
			"--content-max-width": "1200px",
			"--section-padding":   "3rem 2rem",
			// Code
			"--code-bg":      "#1e1e2e",
			"--code-text":    "#e2e8f0",
			"--code-keyword": "#6366f1",
			"--code-string":  "#86efac",
			"--code-comment": "#64748b",
			"--code-number":  "#f59e0b",
			"--code-tag":     "#8b5cf6",
			"--code-attr":    "#94a3b8",
		},
		DarkCSSVars: map[string]string{
			"--color-bg":         "#0f172a",
			"--color-surface":    "#1e293b",
			"--color-surface-2":  "#334155",
			"--color-primary":    "#818cf8",
			"--color-secondary":  "#a78bfa",
			"--color-accent":     "#34d399",
			"--color-danger":     "#f87171",
			"--color-warning":    "#fbbf24",
			"--color-text":       "#f1f5f9",
			"--color-text-muted": "#94a3b8",
			"--color-border":     "#334155",
			"--shadow-card":      "0 1px 4px rgba(0,0,0,0.3), 0 0 0 1px rgba(255,255,255,0.05)",
			"--shadow-btn":       "0 1px 2px rgba(0,0,0,0.3)",
			"--border-color":     "#334155",
			"--code-bg":          "#0f172a",
			"--code-text":        "#e2e8f0",
			"--code-keyword":     "#818cf8",
			"--code-string":      "#86efac",
			"--code-comment":     "#64748b",
			"--code-number":      "#fbbf24",
			"--code-tag":         "#a78bfa",
			"--code-attr":        "#94a3b8",
		},
	},
	{
		Name:        "Swiss International",
		Slug:        "swiss",
		Description: "Helvetica-era grid discipline. Red/black/white. Typography as the only decoration.",
		FontURL:     "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;700&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#ffffff",
			"--color-surface":     "#ffffff",
			"--color-surface-2":   "#f5f5f5",
			"--color-primary":     "#e63329",
			"--color-secondary":   "#1a1a1a",
			"--color-text":        "#1a1a1a",
			"--color-text-muted":  "#767676",
			"--color-border":      "#1a1a1a",
			"--font-display":      "'IBM Plex Sans', sans-serif",
			"--font-body":         "'IBM Plex Sans', sans-serif",
			"--font-mono":         "'Courier New', Courier, monospace",
			"--font-size-display": "5rem",
			"--font-size-heading": "2rem",
			"--font-size-body":    "1rem",
			"--font-size-caption": "0.75rem",
			"--radius-sm":         "0px",
			"--radius-md":         "0px",
			"--radius-lg":         "0px",
			"--shadow-card":       "none",
			"--shadow-btn":        "none",
			"--border-width":      "2px",
			"--border-color":      "#1a1a1a",
			"--content-max-width": "1100px",
			"--section-padding":   "5rem 2rem",
			"--grid-columns":      "12",
			"--baseline":          "8px",
			// Code
			"--code-bg":      "#1a1a1a",
			"--code-text":    "#ffffff",
			"--code-keyword": "#e63329",
			"--code-string":  "#767676",
			"--code-comment": "#444444",
			"--code-number":  "#e63329",
			"--code-tag":     "#ffffff",
			"--code-attr":    "#aaaaaa",
		},
		DarkCSSVars: map[string]string{
			"--color-bg":         "#111111",
			"--color-surface":    "#1a1a1a",
			"--color-surface-2":  "#222222",
			"--color-primary":    "#e63329",
			"--color-secondary":  "#e5e5e5",
			"--color-text":       "#e5e5e5",
			"--color-text-muted": "#999999",
			"--color-border":     "#e5e5e5",
			"--border-color":     "#e5e5e5",
			"--code-bg":          "#0a0a0a",
			"--code-text":        "#e5e5e5",
			"--code-keyword":     "#e63329",
			"--code-string":      "#999999",
			"--code-comment":     "#555555",
			"--code-number":      "#e63329",
			"--code-tag":         "#e5e5e5",
			"--code-attr":        "#bbbbbb",
		},
	},
	{
		Name:        "Terminal",
		Slug:        "terminal",
		Description: "Green-on-black CRT aesthetic. Scanlines, glow, monospace everything.",
		FontURL:     "https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#0a0a0a",
			"--color-surface":     "#111111",
			"--color-surface-2":   "#1a1a1a",
			"--color-primary":     "#00ff41",
			"--color-secondary":   "#00bfff",
			"--color-accent":      "#ffcc00",
			"--color-danger":      "#ff3333",
			"--color-text":        "#00ff41",
			"--color-text-muted":  "#00994d",
			"--color-border":      "#00ff41",
			"--font-display":      "'Fira Code', monospace",
			"--font-body":         "'Fira Code', monospace",
			"--font-mono":         "'Fira Code', monospace",
			"--font-size-display": "2.5rem",
			"--font-size-heading": "1.25rem",
			"--font-size-body":    "0.875rem",
			"--font-size-caption": "0.75rem",
			"--radius-sm":         "0px",
			"--radius-md":         "0px",
			"--radius-lg":         "2px",
			"--shadow-card":       "0 0 10px rgba(0,255,65,0.15)",
			"--shadow-btn":        "0 0 8px rgba(0,255,65,0.2)",
			"--border-width":      "1px",
			"--border-color":      "#00ff41",
			"--content-max-width": "960px",
			"--section-padding":   "3rem 2rem",
			"--code-bg":           "#050505",
			"--code-text":         "#00ff41",
			"--code-keyword":      "#00bfff",
			"--code-string":       "#ffcc00",
			"--code-comment":      "#00994d",
			"--code-number":       "#ff3333",
			"--code-tag":          "#00bfff",
			"--code-attr":         "#00994d",
		},
	},
	{
		Name:        "Retro OS",
		Slug:        "retro",
		Description: "Windowed desktop UI — beveled borders, draggable windows, taskbar.",
		FontURL:     "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;700&family=VT323&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#008080",
			"--color-surface":     "#c0c0c0",
			"--color-surface-2":   "#dfdfdf",
			"--color-primary":     "#000080",
			"--color-secondary":   "#c0c0c0",
			"--color-accent":      "#ffff00",
			"--color-danger":      "#ff0000",
			"--color-text":        "#000000",
			"--color-text-muted":  "#808080",
			"--color-border":      "#808080",
			"--color-highlight":   "#000080",
			"--font-display":      "'VT323', monospace",
			"--font-body":         "'IBM Plex Sans', sans-serif",
			"--font-mono":         "'VT323', monospace",
			"--font-size-display": "2.5rem",
			"--font-size-heading": "1.25rem",
			"--font-size-body":    "0.8125rem",
			"--font-size-caption": "0.6875rem",
			"--radius-sm":         "0px",
			"--radius-md":         "0px",
			"--radius-lg":         "0px",
			"--shadow-card":       "2px 2px 0px #000000",
			"--shadow-btn":        "1px 1px 0px #000000",
			"--border-width":      "2px",
			"--border-color":      "#808080",
			"--content-max-width": "1100px",
			"--section-padding":   "2rem 2rem",
			"--code-bg":           "#000000",
			"--code-text":         "#c0c0c0",
			"--code-keyword":      "#5555ff",
			"--code-string":       "#ffff55",
			"--code-comment":      "#55ff55",
			"--code-number":       "#ff5555",
			"--code-tag":          "#55ffff",
			"--code-attr":         "#808080",
		},
	},
	{
		Name:        "The Daily Style",
		Slug:        "newspaper",
		Description: "Broadsheet editorial layout — serif headlines, multi-column text, drop caps.",
		FontURL:     "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400&family=Source+Serif+4:ital,opsz,wght@0,8..60,300;0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,400&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#faf9f6",
			"--color-surface":     "#ffffff",
			"--color-surface-2":   "#f0efec",
			"--color-primary":     "#c41e1e",
			"--color-secondary":   "#1a1a1a",
			"--color-text":        "#1a1a1a",
			"--color-text-muted":  "#6b6b6b",
			"--color-border":      "#1a1a1a",
			"--font-display":      "'Playfair Display', serif",
			"--font-body":         "'Source Serif 4', serif",
			"--font-mono":         "'Courier New', Courier, monospace",
			"--font-size-display": "4rem",
			"--font-size-heading": "2rem",
			"--font-size-body":    "1.0625rem",
			"--font-size-caption": "0.75rem",
			"--radius-sm":         "0px",
			"--radius-md":         "0px",
			"--radius-lg":         "0px",
			"--shadow-card":       "none",
			"--shadow-btn":        "none",
			"--border-width":      "1px",
			"--border-color":      "#1a1a1a",
			"--content-max-width": "1000px",
			"--section-padding":   "4rem 2rem",
			"--code-bg":           "#1a1a1a",
			"--code-text":         "#faf9f6",
			"--code-keyword":      "#c41e1e",
			"--code-string":       "#6b6b6b",
			"--code-comment":      "#808080",
			"--code-number":       "#c41e1e",
			"--code-tag":          "#1a1a1a",
			"--code-attr":         "#6b6b6b",
		},
		DarkCSSVars: map[string]string{
			"--color-bg":         "#1a1916",
			"--color-surface":    "#2a2926",
			"--color-surface-2":  "#3a3936",
			"--color-primary":    "#e05252",
			"--color-secondary":  "#e0ddd6",
			"--color-text":       "#e0ddd6",
			"--color-text-muted": "#8a8780",
			"--color-border":     "#e0ddd6",
			"--border-color":     "#4a4940",
			"--code-bg":          "#0f0e0c",
			"--code-text":        "#e0ddd6",
			"--code-keyword":     "#e05252",
			"--code-string":      "#8a8780",
			"--code-comment":     "#666666",
			"--code-number":      "#e05252",
			"--code-tag":         "#e0ddd6",
			"--code-attr":        "#8a8780",
		},
	},
	{
		Name:        "Shelf",
		Slug:        "shelf",
		Description: "Warm, scannable, list-driven. A reading companion built on linen tones, literary type, and triple-encoded accessibility.",
		FontURL:     "https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;1,9..40,400&family=JetBrains+Mono:wght@400&family=Lora:ital,wght@0,400;0,600;1,400&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#faf8f5",
			"--color-surface":     "#f2ece4",
			"--color-surface-2":   "#ebe4d9",
			"--color-primary":     "#5a7247",
			"--color-secondary":   "#2c2119",
			"--color-accent":      "#c08b3e",
			"--color-accent-2":    "#b86842",
			"--color-info":        "#5b7a94",
			"--color-success":     "#6a9a6e",
			"--color-danger":      "#a8473a",
			"--color-text":        "#2c2119",
			"--color-text-muted":  "#7a6e60",
			"--color-border":      "#e5ddd3",
			"--font-display":      "'Lora', serif",
			"--font-body":         "'DM Sans', sans-serif",
			"--font-mono":         "'JetBrains Mono', monospace",
			"--font-size-display": "2rem",
			"--font-size-heading": "1.25rem",
			"--font-size-body":    "0.875rem",
			"--font-size-caption": "0.75rem",
			"--radius-sm":         "4px",
			"--radius-md":         "8px",
			"--radius-lg":         "12px",
			"--shadow-card":       "0 1px 4px rgba(44,33,25,0.08)",
			"--shadow-btn":        "0 1px 2px rgba(44,33,25,0.06)",
			"--border-width":      "1px",
			"--border-color":      "#e5ddd3",
			"--content-max-width": "1000px",
			"--section-padding":   "3rem 2rem",
			"--code-bg":           "#2c2119",
			"--code-text":         "#e8e2d8",
			"--code-keyword":      "#7a9a66",
			"--code-string":       "#d4a04a",
			"--code-comment":      "#7a6e60",
			"--code-number":       "#c08b3e",
			"--code-tag":          "#5b7a94",
			"--code-attr":         "#a99e8e",
		},
		DarkCSSVars: map[string]string{
			"--color-bg":         "#1a1714",
			"--color-surface":    "#242019",
			"--color-surface-2":  "#2e2a22",
			"--color-primary":    "#7a9a66",
			"--color-secondary":  "#e8e2d8",
			"--color-accent":     "#d4a04a",
			"--color-accent-2":   "#d47e56",
			"--color-info":       "#7a9ab4",
			"--color-success":    "#8aba8e",
			"--color-danger":     "#c86a5e",
			"--color-text":       "#e8e2d8",
			"--color-text-muted": "#a99e8e",
			"--color-border":     "#3d362c",
			"--shadow-card":      "0 1px 4px rgba(0,0,0,0.3)",
			"--shadow-btn":       "0 1px 2px rgba(0,0,0,0.2)",
			"--border-color":     "#3d362c",
			"--code-bg":          "#13110e",
			"--code-text":        "#e8e2d8",
			"--code-keyword":     "#8aba8e",
			"--code-string":      "#d4a04a",
			"--code-comment":     "#6e6356",
			"--code-number":      "#d4a04a",
			"--code-tag":         "#7a9ab4",
			"--code-attr":        "#a99e8e",
		},
	},
	{
		Name:        "Tracker",
		Slug:        "tracker",
		Description: "Less, but better. A goal tracker built on restraint, clarity, and purposeful color.",
		FontURL:     "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap",
		CSSVars: map[string]string{
			"--color-bg":          "#f7f6f3",
			"--color-surface":     "#ffffff",
			"--color-surface-2":   "#edecea",
			"--color-primary":     "#d45b2c",
			"--color-secondary":   "#2c2c2c",
			"--color-accent":      "#3a8a5c",
			"--color-warning":     "#c4880b",
			"--color-danger":      "#b53d2e",
			"--color-info":        "#3d7ec7",
			"--color-text":        "#2c2c2c",
			"--color-text-muted":  "#8a8780",
			"--color-border":      "#dddbd6",
			"--font-display":      "'Plus Jakarta Sans', sans-serif",
			"--font-body":         "'Plus Jakarta Sans', sans-serif",
			"--font-mono":         "'Courier New', Courier, monospace",
			"--font-size-display": "2.25rem",
			"--font-size-heading": "1rem",
			"--font-size-body":    "0.875rem",
			"--font-size-caption": "0.75rem",
			"--radius-sm":         "4px",
			"--radius-md":         "6px",
			"--radius-lg":         "8px",
			"--shadow-card":       "0 1px 3px rgba(0,0,0,0.06)",
			"--shadow-btn":        "0 1px 2px rgba(0,0,0,0.04)",
			"--border-width":      "1px",
			"--border-color":      "#dddbd6",
			"--content-max-width": "1100px",
			"--section-padding":   "3rem 2rem",
			"--code-bg":           "#2c2c2c",
			"--code-text":         "#e8e6e1",
			"--code-keyword":      "#d45b2c",
			"--code-string":       "#3a8a5c",
			"--code-comment":      "#8a8780",
			"--code-number":       "#c4880b",
			"--code-tag":          "#3d7ec7",
			"--code-attr":         "#8a8780",
		},
		DarkCSSVars: map[string]string{
			"--color-bg":         "#1c1b18",
			"--color-surface":    "#2c2b28",
			"--color-surface-2":  "#3c3b38",
			"--color-primary":    "#e8714a",
			"--color-secondary":  "#d4d1cc",
			"--color-accent":     "#5aaa7c",
			"--color-warning":    "#d4a020",
			"--color-danger":     "#d4604e",
			"--color-info":       "#5a9ee7",
			"--color-text":       "#d4d1cc",
			"--color-text-muted": "#8a8780",
			"--color-border":     "#4a4840",
			"--shadow-card":      "0 1px 3px rgba(0,0,0,0.3)",
			"--shadow-btn":       "0 1px 2px rgba(0,0,0,0.2)",
			"--border-color":     "#4a4840",
			"--code-bg":          "#141310",
			"--code-text":        "#d4d1cc",
			"--code-keyword":     "#e8714a",
			"--code-string":      "#5aaa7c",
			"--code-comment":     "#8a8780",
			"--code-number":      "#d4a020",
			"--code-tag":         "#5a9ee7",
			"--code-attr":        "#8a8780",
		},
	},
}

// BuildCSSVars generates ":root" CSS variable declarations from a map.
// Keys are sorted for deterministic output.
func BuildCSSVars(vars map[string]string) string {
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	var sb strings.Builder
	for _, k := range keys {
		sb.WriteString(k)
		sb.WriteString(":")
		sb.WriteString(vars[k])
		sb.WriteString(";")
	}
	return sb.String()
}

// BuildDarkCSS generates a [data-theme="dark"] block for guides with dark variants.
// Returns an empty string if darkVars is nil.
func BuildDarkCSS(darkVars map[string]string) string {
	if darkVars == nil {
		return ""
	}
	return "[data-theme=\"dark\"]{" + BuildCSSVars(darkVars) + "}"
}

// BySlug looks up a guide by its URL slug.
func BySlug(slug string) (Guide, bool) {
	for _, g := range All {
		if g.Slug == slug {
			return g, true
		}
	}
	return Guide{}, false
}
